package com.wanda.credit.ds.client.guozt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.commons.codec.binary.Base64;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-24T16:28:31.319+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class QueryValidatorServices_QueryValidatorServices_Client {

    private static final QName SERVICE_NAME = new QName("http://app.service.validator.businesses.gboss.id5.cn", "QueryValidatorServicesService");

    private QueryValidatorServices_QueryValidatorServices_Client() {
    }

}
